[package]
name = "design-tokens"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
lazy_static = "1.5"

[dev-dependencies]
serde_json = "1.0"
